// All static catalog data used by the simulator: connection presets,
// their display names/technology blurbs/default icons, server locations,
// weather profiles, IP address types, and failure-simulation presets.
// No DOM access happens in this file.

// ---------- Connection presets (speed/latency/jitter/loss per tier) ----------
  const presets = {
    // Fiber (FTTH)
    fiber100:     {dl:100,  ul:100,  ping:7,   jitter:2,  ins:6,  pl:0.0},
    fiber500:     {dl:500,  ul:500,  ping:5,   jitter:1,  ins:5,  pl:0.0},
    fiber1g:      {dl:940,  ul:880,  ping:5,   jitter:1,  ins:5,  pl:0.0},
    fiber2_5g:    {dl:2300, ul:2300, ping:4,   jitter:1,  ins:4,  pl:0.0},
    fiber5g:      {dl:5000, ul:5000, ping:3,   jitter:1,  ins:3,  pl:0.0},
    fiber10g:     {dl:9400, ul:9400, ping:3,   jitter:1,  ins:3,  pl:0.0},
    // Cable
    cablebasic:   {dl:100,  ul:10,   ping:22,  jitter:5,  ins:14, pl:0.15},
    cable:        {dl:300,  ul:20,   ping:18,  jitter:4,  ins:12, pl:0.1},
    cablegig:     {dl:1200, ul:35,   ping:14,  jitter:3,  ins:9,  pl:0.05},
    cable2gig:    {dl:2000, ul:100,  ping:12,  jitter:3,  ins:8,  pl:0.05},
    cable4gig:    {dl:4000, ul:400,  ping:10,  jitter:2,  ins:7,  pl:0.03},
    // DSL
    adsl2:        {dl:20,   ul:1,    ping:38,  jitter:8,  ins:20, pl:0.4},
    dsl:          {dl:40,   ul:10,   ping:35,  jitter:6,  ins:16, pl:0.3},
    gfast:        {dl:350,  ul:50,   ping:16,  jitter:4,  ins:12, pl:0.15},
    // WISP
    wisp10:       {dl:10,   ul:3,    ping:28,  jitter:13, ins:36, pl:1.0},
    wisp20:       {dl:20,   ul:5,    ping:24,  jitter:11, ins:32, pl:0.8},
    wisp45:       {dl:45,   ul:10,   ping:20,  jitter:9,  ins:28, pl:0.6},
    wisp60:       {dl:60,   ul:12,   ping:18,  jitter:8,  ins:26, pl:0.5},
    wisp100:      {dl:100,  ul:20,   ping:16,  jitter:7,  ins:24, pl:0.4},
    wisppro:      {dl:150,  ul:30,   ping:13,  jitter:5,  ins:18, pl:0.3},
    // Mobile & cellular
    edge:         {dl:0.2,  ul:0.1,  ping:420, jitter:90, ins:50, pl:2.0},
    umts:         {dl:1.5,  ul:0.5,  ping:150, jitter:45, ins:42, pl:1.5},
    hspa:         {dl:8,    ul:2,    ping:110, jitter:32, ins:36, pl:1.0},
    lte:          {dl:45,   ul:12,   ping:45,  jitter:14, ins:30, pl:0.6},
    ltea:         {dl:120,  ul:25,   ping:32,  jitter:9,  ins:20, pl:0.3},
    ltecat18:     {dl:300,  ul:50,   ping:26,  jitter:8,  ins:18, pl:0.25},
    mobile5g:     {dl:250,  ul:30,   ping:28,  jitter:11, ins:24, pl:0.4},
    sa5g:         {dl:900,  ul:100,  ping:8,   jitter:3,  ins:14, pl:0.2},
    mmwave:       {dl:1800, ul:120,  ping:9,   jitter:6,  ins:34, pl:0.5},
    fiveg_adv:    {dl:2500, ul:300,  ping:5,   jitter:2,  ins:12, pl:0.15},
    fixedwireless:{dl:300,  ul:50,   ping:20,  jitter:8,  ins:20, pl:0.3},
    cbrs:         {dl:100,  ul:20,   ping:18,  jitter:7,  ins:19, pl:0.3},
    weaksignal:   {dl:5,    ul:2,    ping:180, jitter:70, ins:55, pl:3.0},
    // Satellite
    starlink:     {dl:220,  ul:25,   ping:45,  jitter:9,  ins:22, pl:0.5},
    starlinkpro:  {dl:350,  ul:40,   ping:35,  jitter:7,  ins:18, pl:0.3},
    meo:          {dl:150,  ul:20,   ping:150, jitter:20, ins:28, pl:0.6},
    satellite:    {dl:25,   ul:3,    ping:600, jitter:35, ins:42, pl:1.0},
    // Shared, legacy & novelty
    dialup:       {dl:0.056,ul:0.033,ping:250, jitter:60, ins:45, pl:1.5},
    isdn:         {dl:0.128,ul:0.128,ping:120, jitter:25, ins:22, pl:0.5},
    powerline:    {dl:80,   ul:20,   ping:12,  jitter:9,  ins:30, pl:0.4},
    meshnet:      {dl:60,   ul:15,   ping:22,  jitter:16, ins:34, pl:0.8},
    campuswifi:   {dl:200,  ul:50,   ping:14,  jitter:6,  ins:18, pl:0.3},
    publicwifi:   {dl:25,   ul:5,    ping:35,  jitter:28, ins:45, pl:1.2},
    hotelwifi:    {dl:15,   ul:3,    ping:60,  jitter:40, ins:52, pl:1.8},
    // Business & emerging tech
    t1line:       {dl:1.5,  ul:1.5,  ping:12,  jitter:2,  ins:4,  pl:0.02},
    efm:          {dl:50,   ul:50,   ping:10,  jitter:2,  ins:6,  pl:0.05},
    metroe:       {dl:1000, ul:1000, ping:5,   jitter:1,  ins:3,  pl:0.02},
    sdwan:        {dl:500,  ul:500,  ping:8,   jitter:2,  ins:5,  pl:0.03},
    urllc:        {dl:150,  ul:150,  ping:2,   jitter:0.5,ins:3,  pl:0.01},
    tvws:         {dl:12,   ul:4,    ping:35,  jitter:15, ins:30, pl:0.8},
    sixg:         {dl:9800, ul:9800, ping:1,   jitter:4,  ins:38, pl:1.2},
    fso:          {dl:2500, ul:2500, ping:2,   jitter:2,  ins:22, pl:0.4},
    submarine:    {dl:9800, ul:9800, ping:2,   jitter:0.5,ins:2,  pl:0.01},
    vsat:         {dl:10,   ul:3,    ping:650, jitter:60, ins:46, pl:2.0},
    nbiot:        {dl:0.06, ul:0.06, ping:300, jitter:80, ins:40, pl:2.5},
    lorawan:      {dl:0.01, ul:0.01, ping:900, jitter:150,ins:30, pl:3.0},
    // Data center & backbone
    dc10g:        {dl:10000,  ul:10000,  ping:1,   jitter:0.3,  ins:2,   pl:0.005},
    dc25g:        {dl:25000,  ul:25000,  ping:1,   jitter:0.3,  ins:2,   pl:0.005},
    dc40g:        {dl:40000,  ul:40000,  ping:0.6, jitter:0.2,  ins:1.5, pl:0.003},
    dc100g:       {dl:100000, ul:100000, ping:0.5, jitter:0.2,  ins:1.5, pl:0.002},
    dc400g:       {dl:400000, ul:400000, ping:0.4, jitter:0.15, ins:1.2, pl:0.001},
    zrplus:       {dl:800000, ul:800000, ping:0.3, jitter:0.1,  ins:1,   pl:0.0005},
    // Real-world-inspired tiers
    fiber200:     {dl:200,    ul:200,    ping:6,   jitter:1,    ins:6,   pl:0.02},
    cable200:     {dl:200,    ul:10,     ping:20,  jitter:5,    ins:13,  pl:0.12},
    cable500:     {dl:500,    ul:20,     ping:16,  jitter:4,    ins:10,  pl:0.08},
    basicdsl:     {dl:6,      ul:0.5,    ping:45,  jitter:10,   ins:22,  pl:0.5},
    basicbroadband:{dl:25,    ul:3,      ping:30,  jitter:8,    ins:18,  pl:0.4},
    fiveghomebasic:{dl:75,    ul:12,     ping:25,  jitter:10,   ins:24,  pl:0.4},
    starlinkmaritime:{dl:180, ul:20,     ping:55,  jitter:25,   ins:40,  pl:1.2},
    starlinkaviation:{dl:150, ul:20,     ping:60,  jitter:30,   ins:42,  pl:1.3},
    throttledmobile:{dl:0.128,ul:0.064,  ping:250, jitter:60,   ins:40,  pl:1.5},
    // Niche & retro tech
    lifi:         {dl:1000,   ul:1000,   ping:2,   jitter:1,    ins:15,  pl:0.3},
    tokenring:    {dl:16,     ul:16,     ping:3,   jitter:1,    ins:5,   pl:0.05},
    bluetooth:    {dl:2,      ul:1,      ping:60,  jitter:25,   ins:35,  pl:1.0},
    zigbee:       {dl:0.25,   ul:0.25,   ping:80,  jitter:30,   ins:35,  pl:1.5},
    thunderbolt:  {dl:10000,  ul:10000,  ping:0.5, jitter:0.2,  ins:3,   pl:0.01},
    // PON fiber types & municipal
    gpon_std:     {dl:1000,   ul:500,    ping:5,   jitter:1,    ins:5,   pl:0.02},
    xgspon_std:   {dl:8000,   ul:8000,   ping:3,   jitter:0.5,  ins:3,   pl:0.01},
    pon25g:       {dl:20000,  ul:20000,  ping:2,   jitter:0.3,  ins:2,   pl:0.005},
    munifiber:    {dl:500,    ul:500,    ping:6,   jitter:1.5,  ins:9,   pl:0.05},
    // Wi-Fi generations & everyday scenarios
    wifi4:        {dl:100,    ul:100,    ping:4,   jitter:2,    ins:20,  pl:0.3},
    wifi5:        {dl:400,    ul:400,    ping:3,   jitter:1.5,  ins:14,  pl:0.15},
    wifi6:        {dl:800,    ul:800,    ping:2,   jitter:1,    ins:10,  pl:0.08},
    wifi6e:       {dl:1500,   ul:1500,   ping:1.5, jitter:0.8,  ins:7,   pl:0.05},
    wifi7:        {dl:3000,   ul:3000,   ping:1,   jitter:0.5,  ins:5,   pl:0.03},
    oldrouter24:  {dl:25,     ul:10,     ping:8,   jitter:6,    ins:35,  pl:1.2},
    apartmentwifi:{dl:60,     ul:20,     ping:10,  jitter:12,   ins:40,  pl:1.5},
    homemesh:     {dl:500,    ul:500,    ping:2,   jitter:1,    ins:8,   pl:0.1},
    gamingethernet:{dl:500,   ul:50,     ping:4,   jitter:0.5,  ins:3,   pl:0.01},
    publichotspot:{dl:15,     ul:3,      ping:45,  jitter:20,   ins:42,  pl:1.6},
    wifidirect:   {dl:250,    ul:250,    ping:3,   jitter:1,    ins:10,  pl:0.1},
    dormethernet: {dl:200,    ul:50,     ping:8,   jitter:4,    ins:20,  pl:0.4},
    plwifiext:    {dl:40,     ul:10,     ping:12,  jitter:8,    ins:32,  pl:0.9},
    meshdeadzone: {dl:15,     ul:5,      ping:15,  jitter:15,   ins:45,  pl:1.8},
    // Microwave backhaul
    licensedmw:   {dl:500,    ul:500,    ping:4,   jitter:1,    ins:10,  pl:0.1},
    eband:        {dl:10000,  ul:10000,  ping:2,   jitter:0.5,  ins:15,  pl:0.15},
    ptp5g_af:     {dl:500,    ul:500,    ping:2,   jitter:0.5,  ins:12,  pl:0.1},
    ptp24g_af:    {dl:1000,   ul:1000,   ping:1.5, jitter:0.4,  ins:10,  pl:0.08},
    ptp60g_af:    {dl:1500,   ul:1500,   ping:1,   jitter:0.3,  ins:20,  pl:0.2},
    ptp11g_af:    {dl:1000,   ul:1000,   ping:1,   jitter:0.3,  ins:8,   pl:0.05},
    // Misc additions
    starlinkmini: {dl:90,     ul:10,     ping:50,  jitter:20,   ins:35,  pl:1.0},
    directcell:   {dl:0.02,   ul:0.01,   ping:1500,jitter:300,  ins:50,  pl:3.0},
    openran:      {dl:300,    ul:300,    ping:6,   jitter:2,    ins:12,  pl:0.2},
    corpvpn:      {dl:150,    ul:20,     ping:35,  jitter:10,   ins:22,  pl:0.4},
  };

// ---------- Human-readable names for each preset ----------
  const presetNames = {
    fiber100:'Fiber 100', fiber500:'Fiber 500', fiber1g:'Fiber (1G)', fiber2_5g:'Fiber (2.5G)',
    fiber5g:'Fiber (5G)', fiber10g:'Fiber (10G)',
    cablebasic:'Cable Basic', cable:'Cable', cablegig:'Cable Gig', cable2gig:'Cable Multi-Gig (2G)',
    cable4gig:'Cable Multi-Gig (4G)',
    adsl2:'ADSL2+', dsl:'VDSL2', gfast:'G.fast',
    wisp10:'WISP 10', wisp20:'WISP 20', wisp45:'WISP 45', wisp60:'WISP 60', wisp100:'WISP 100', wisppro:'WISP Pro',
    edge:'2G EDGE', umts:'3G UMTS', hspa:'3G HSPA+', lte:'4G LTE', ltea:'4G LTE-Advanced', ltecat18:'4G LTE Cat18',
    mobile5g:'5G Sub-6', sa5g:'5G SA', mmwave:'5G mmWave', fiveg_adv:'5G-Advanced',
    fixedwireless:'5G Fixed Wireless', cbrs:'CBRS Private LTE', weaksignal:'Roaming / Weak Signal',
    starlink:'LEO Satellite', starlinkpro:'LEO Satellite Pro', meo:'MEO Satellite', satellite:'GEO Satellite',
    dialup:'Dial-Up', isdn:'ISDN', powerline:'Powerline', meshnet:'Community Mesh', campuswifi:'Campus Wi-Fi',
    publicwifi:'Public Wi-Fi', hotelwifi:'Hotel Wi-Fi',
    t1line:'T1 Leased Line', efm:'EFM Business Line', metroe:'Metro Ethernet', sdwan:'SD-WAN',
    urllc:'5G URLLC Slice', tvws:'TV White Space', sixg:'6G Preview',
    fso:'Free-Space Optical', submarine:'Submarine Cable', vsat:'VSAT', nbiot:'NB-IoT', lorawan:'LoRaWAN',
    dc10g:'10GbE', dc25g:'25GbE', dc40g:'40GbE', dc100g:'100GbE', dc400g:'400GbE', zrplus:'800ZR+',
    fiber200:'Fiber 200', cable200:'Cable 200', cable500:'Cable 500', basicdsl:'Basic DSL',
    basicbroadband:'Basic Broadband', fiveghomebasic:'5G Home Internet',
    starlinkmaritime:'LEO Satellite (Maritime)', starlinkaviation:'LEO Satellite (Aviation)',
    throttledmobile:'Throttled Mobile',
    lifi:'Li-Fi', tokenring:'Token Ring', bluetooth:'Bluetooth Tethering', zigbee:'Zigbee', thunderbolt:'Thunderbolt Bridge',
    gpon_std:'GPON', xgspon_std:'XGS-PON', pon25g:'25G PON', munifiber:'Municipal Fiber',
    wifi4:'Wi-Fi 4', wifi5:'Wi-Fi 5', wifi6:'Wi-Fi 6', wifi6e:'Wi-Fi 6E', wifi7:'Wi-Fi 7',
    oldrouter24:'Old Router (2.4GHz)', apartmentwifi:'Apartment Wi-Fi', homemesh:'Home Mesh',
    gamingethernet:'Gaming Ethernet', publichotspot:'Public Hotspot', wifidirect:'Wi-Fi Direct',
    dormethernet:'Dorm Ethernet', plwifiext:'Powerline Wi-Fi Extender', meshdeadzone:'Mesh Dead Zone',
    licensedmw:'Licensed Microwave', eband:'E-band Backhaul',
    ptp5g_af:'PtP 5GHz (airFiber-class)', ptp24g_af:'PtP 24GHz (airFiber-class)',
    ptp60g_af:'PtP 60GHz (GigaBeam-class)', ptp11g_af:'PtP 11GHz Licensed (airFiber-class)',
    starlinkmini:'Starlink Mini', directcell:'Direct-to-Cell', openran:'Private 5G (OpenRAN)', corpvpn:'Corporate VPN',
    custom:'Custom'
  };

// ---------- Technology description shown in the 'Tech:' line ----------
  const presetTech = {
    fiber100:'GPON — ITU-T G.984, entry FTTH tier',
    fiber500:'XGS-PON — 500 Mbps symmetrical tier',
    fiber1g:'GPON — ITU-T G.984, 1 Gbps symmetrical',
    fiber2_5g:'XGS-PON — 2.5 Gbps symmetrical',
    fiber5g:'NG-PON2 — 5 Gbps symmetrical',
    fiber10g:'XGS-PON / 10G-EPON — 10 Gbps symmetrical',
    cablebasic:'DOCSIS 3.0 — Coaxial HFC, entry tier',
    cable:'DOCSIS 3.0 — Coaxial HFC',
    cablegig:'DOCSIS 3.1 — Coaxial HFC, Gigabit tier',
    cable2gig:'DOCSIS 3.1 — Coaxial HFC, multi-gig tier',
    cable4gig:'DOCSIS 4.0 — Full-duplex coaxial HFC',
    adsl2:'ADSL2+ — Copper twisted pair',
    dsl:'VDSL2 — Copper twisted pair',
    gfast:'G.fast — Copper, short-loop FTTdp',
    wisp10:'WISP — 2.4/5 GHz PtMP Radio, 10 Mbps tier',
    wisp20:'WISP — 2.4/5 GHz PtMP Radio, 20 Mbps tier',
    wisp45:'WISP — 5 GHz PtMP Radio, 45 Mbps tier',
    wisp60:'WISP — 5 GHz PtMP Radio, 60 Mbps tier',
    wisp100:'WISP — 5 GHz PtMP Radio, 100 Mbps tier',
    wisppro:'WISP — Licensed microwave / 5 GHz PtP',
    edge:'2G EDGE — Enhanced GPRS',
    umts:'3G UMTS — WCDMA',
    hspa:'3G HSPA+ — Dual-Carrier',
    lte:'4G LTE — Cat4/Cat6',
    ltea:'4G LTE-Advanced — Cat12+, carrier aggregation',
    ltecat18:'4G LTE Cat18 — Gigabit LTE, 5x CA + 4x4 MIMO',
    mobile5g:'5G NSA (Non-Standalone) — n41/n77 sub-6 GHz',
    sa5g:'5G SA (Standalone) — n78 band, standalone core',
    mmwave:'5G NR mmWave — n260/n261 bands',
    fiveg_adv:'5G-Advanced — 3GPP Release 18',
    fixedwireless:'5G FWA — Sub-6 GHz CPE antenna',
    cbrs:'CBRS Private LTE — Band 48 (3.5 GHz)',
    weaksignal:'Mobile — degraded signal / roaming',
    starlink:'LEO Satellite — Ku/Ka-band phased array',
    starlinkpro:'LEO Satellite — Priority tier, Ku/Ka-band',
    meo:'MEO Satellite — Ka-band, ~8,000 km orbit',
    satellite:'GEO Satellite — Ku-band dish',
    dialup:'V.92 Analog Modem — PSTN',
    isdn:'ISDN BRI — 2×64 kbps B-channels',
    powerline:'IEEE 1901 (HomePlug AV2) — electrical wiring',
    meshnet:'802.11s Mesh — multi-hop Wi-Fi',
    campuswifi:'802.11ax (Wi-Fi 6) — enterprise AP',
    publicwifi:'802.11n — shared, congested AP',
    hotelwifi:'802.11ac — oversubscribed gateway',
    t1line:'T1 (DS1) — 1.544 Mbps symmetrical, TDM circuit',
    efm:'EFM (IEEE 802.3ah) — bonded copper pairs',
    metroe:'Metro Ethernet — Carrier Ethernet 2.0, MEF-certified',
    sdwan:'SD-WAN — multi-path bonded circuits w/ forward error correction',
    urllc:'5G URLLC — dedicated network slice, sub-1ms air interface target',
    tvws:'TV White Space — unlicensed UHF spectrum (470–698 MHz)',
    sixg:'6G (Experimental Trial) — sub-THz research band, pre-standard',
    fso:'Free-Space Optical (FSO) — laser point-to-point, weather-sensitive',
    submarine:'Submarine Cable — wholesale transit, 100G coherent wave',
    vsat:'VSAT — C-band, remote/field terminal',
    nbiot:'NB-IoT — 3GPP LPWAN, narrowband channel',
    lorawan:'LoRaWAN — unlicensed sub-GHz LPWAN',
    dc10g:'10 Gigabit Ethernet — SFP+ optical transceiver',
    dc25g:'25 Gigabit Ethernet — SFP28 optical transceiver',
    dc40g:'40 Gigabit Ethernet — QSFP+ optical transceiver',
    dc100g:'100 Gigabit Ethernet — QSFP28, backbone/core link',
    dc400g:'400 Gigabit Ethernet — QSFP-DD, core network link',
    zrplus:'800ZR+ — coherent DWDM transport, single wavelength',
    fiber200:'GPON — ITU-T G.984, 200 Mbps tier',
    cable200:'DOCSIS 3.0 — Coaxial HFC, 200 Mbps tier',
    cable500:'DOCSIS 3.1 — Coaxial HFC, 500 Mbps tier',
    basicdsl:'ADSL — Copper twisted pair, entry tier',
    basicbroadband:'VDSL/Cable — legacy FCC broadband minimum (25/3)',
    fiveghomebasic:'5G FWA — Sub-6 GHz CPE, capped home internet plan',
    starlinkmaritime:'LEO Satellite — stabilized marine antenna array',
    starlinkaviation:'LEO Satellite — in-flight phased-array antenna',
    throttledmobile:'Mobile — throttled after monthly data cap',
    lifi:'Li-Fi — visible light communication (VLC), line-of-sight',
    tokenring:'Token Ring — IEEE 802.5, legacy LAN',
    bluetooth:'Bluetooth PAN — personal area network tethering',
    zigbee:'Zigbee — IEEE 802.15.4 mesh, smart home',
    thunderbolt:'Thunderbolt Bridge — direct peer-to-peer link (USB4)',
    gpon_std:'GPON — ITU-T G.984, shared PON (2.5G/1.25G)',
    xgspon_std:'XGS-PON — 10G symmetrical shared PON',
    pon25g:'25G PON — next-gen symmetrical shared PON',
    munifiber:'GPON — municipal/community-owned fiber co-op',
    wifi4:'Wi-Fi 4 (802.11n) — 2.4/5 GHz, single-band router',
    wifi5:'Wi-Fi 5 (802.11ac) — 5 GHz, MU-MIMO',
    wifi6:'Wi-Fi 6 (802.11ax) — 2.4/5 GHz, OFDMA',
    wifi6e:'Wi-Fi 6E — adds 6 GHz band, less congestion',
    wifi7:'Wi-Fi 7 (802.11be) — Multi-Link Operation (MLO), 320 MHz channels',
    oldrouter24:'Wi-Fi 4 (802.11n) — 2.4 GHz only, aging consumer router',
    apartmentwifi:'Wi-Fi — 2.4/5 GHz, dense multi-unit interference',
    homemesh:'Wi-Fi 6 Mesh — tri-band mesh system, wired backhaul',
    gamingethernet:'Gigabit Ethernet — direct wired LAN connection',
    publichotspot:'Wi-Fi — carrier/venue-provided public hotspot',
    wifidirect:'Wi-Fi Direct — device-to-device, no access point',
    dormethernet:'Gigabit Ethernet — oversubscribed dorm/campus LAN',
    plwifiext:'Wi-Fi Extender — powerline (HomePlug) backhaul',
    meshdeadzone:'Wi-Fi Mesh — far node, weak backhaul link',
    licensedmw:'Licensed Microwave — point-to-point backhaul link',
    eband:'E-band (70/80 GHz) — ultra-high-capacity mmWave backhaul',
    ptp5g_af:'PtP Wireless Backhaul — 5 GHz (airFiber-class radio)',
    ptp24g_af:'PtP Wireless Backhaul — 24 GHz license-light (airFiber-class radio)',
    ptp60g_af:'PtP Wireless Backhaul — 60 GHz (GigaBeam-class radio), rain-fade sensitive',
    ptp11g_af:'PtP Wireless Backhaul — 11 GHz licensed (airFiber-class radio)',
    starlinkmini:'LEO Satellite (Compact Terminal) — Starlink Mini-class',
    directcell:'Satellite Direct-to-Cell — LEO-to-phone, narrowband',
    openran:'OpenRAN Private 5G — disaggregated small-cell network',
    corpvpn:'IPsec/SSL VPN — tunneled over residential broadband',
  };

// ---------- Default network icon per preset ----------
  const presetIconDefault = {
    fiber100:'fibre', fiber500:'fibre', fiber1g:'fibre', fiber2_5g:'fibre', fiber5g:'fibre', fiber10g:'fibre',
    cablebasic:'cable', cable:'cable', cablegig:'cable', cable2gig:'cable', cable4gig:'cable',
    adsl2:'internet', dsl:'internet', gfast:'internet',
    wisp10:'tower', wisp20:'tower', wisp45:'tower', wisp60:'tower', wisp100:'tower', wisppro:'tower',
    edge:'two_g', umts:'three_g', hspa:'three_g',
    lte:'four_g', ltea:'four_g', ltecat18:'four_g',
    mobile5g:'five_g', sa5g:'five_g', mmwave:'five_g', fiveg_adv:'five_g', fixedwireless:'five_g', cbrs:'tower',
    weaksignal:'four_g',
    starlink:'satellite', starlinkpro:'satellite', meo:'satellite', satellite:'satellite',
    dialup:'internet', isdn:'internet', powerline:'cable', meshnet:'mesh',
    campuswifi:'wifi', publicwifi:'wifi', hotelwifi:'wifi',
    t1line:'enterprise', efm:'enterprise', metroe:'enterprise', sdwan:'mesh',
    urllc:'latency', tvws:'tower', sixg:'rocket',
    fso:'laser', submarine:'submarinecable', vsat:'satellite', nbiot:'chip', lorawan:'chip',
    dc10g:'switch', dc25g:'switch', dc40g:'switch', dc100g:'switch', dc400g:'switch', zrplus:'laser',
    fiber200:'fibre', cable200:'cable', cable500:'cable', basicdsl:'internet',
    basicbroadband:'internet', fiveghomebasic:'five_g',
    starlinkmaritime:'satellite', starlinkaviation:'satellite', throttledmobile:'three_g',
    lifi:'laser', tokenring:'cable', bluetooth:'bluetooth', zigbee:'chip', thunderbolt:'thunderbolt',
    gpon_std:'fibre', xgspon_std:'fibre', pon25g:'fibre', munifiber:'fibre',
    wifi4:'wifi', wifi5:'wifi', wifi6:'wifi', wifi6e:'wifi', wifi7:'wifi',
    oldrouter24:'wifi', apartmentwifi:'wifi', homemesh:'mesh', gamingethernet:'cable',
    publichotspot:'wifi', wifidirect:'wifi', dormethernet:'cable', plwifiext:'wifi', meshdeadzone:'mesh',
    licensedmw:'tower', eband:'tower',
    ptp5g_af:'tower', ptp24g_af:'tower', ptp60g_af:'tower', ptp11g_af:'tower',
    starlinkmini:'satellite', directcell:'satellite', openran:'five_g', corpvpn:'enterprise',
  };

// ---------- Server locations / fictional ISPs by country ----------
  const locationMeta = {
    auto:{label:'Auto (Nearest)', extra:0},
    // Europe
    al:{label:'AlbaTelecom+ (Tirana, Albania)', extra:24},
    ad:{label:'AndoCom (Andorra la Vella, Andorra)', extra:14},
    at:{label:'A1 Telekonn (Vienna, Austria)', extra:11},
    at2:{label:'Magentaa Österreich (Vienna, Austria)', extra:12},
    at3:{label:'Dreii Österreich (Vienna, Austria)', extra:13},
    by:{label:'BeloTelecom (Minsk, Belarus)', extra:34},
    be:{label:'Proximost (Brussels, Belgium)', extra:7},
    be2:{label:'Orangina Belgique (Brussels, Belgium)', extra:8},
    be3:{label:'TeleNyet Belgium (Brussels, Belgium)', extra:9},
    ba:{label:'BiH Telekonn (Sarajevo, Bosnia and Herzegovina)', extra:22},
    bg:{label:'VivaConn (Sofia, Bulgaria)', extra:26},
    hr:{label:'Hrvatski Telekonn (Zagreb, Croatia)', extra:19},
    hr2:{label:'A1-ish Hrvatska (Zagreb, Croatia)', extra:20},
    hr3:{label:'TeleMock Hrvatska (Zagreb, Croatia)', extra:21},
    cy:{label:'CyTech Communications (Nicosia, Cyprus)', extra:36},
    cz:{label:'O3 Czechia (Prague, Czechia)', extra:13},
    cz2:{label:'T-Mobil-ish Česko (Prague, Czechia)', extra:14},
    cz3:{label:'VodaFoam Česko (Prague, Czechia)', extra:15},
    dk:{label:'eTDC Nordic (Copenhagen, Denmark)', extra:14},
    dk2:{label:'TeleNorge Danmark (Copenhagen, Denmark)', extra:15},
    dk3:{label:'TeliaNot Danmark (Copenhagen, Denmark)', extra:16},
    ee:{label:'Telio Eesti (Tallinn, Estonia)', extra:27},
    fi:{label:'Elisar Oyj (Helsinki, Finland)', extra:26},
    fi2:{label:'TeliaNot Suomi (Helsinki, Finland)', extra:27},
    fi3:{label:'DeeEnAy Suomi (Helsinki, Finland)', extra:28},
    fr:{label:'Orangina Télécom (Paris, France)', extra:9},
    fr2:{label:'SFRaudband (Paris, France)', extra:10},
    fr3:{label:'Freeloader Télécom (Paris, France)', extra:8},
    de:{label:'DoitscheTelekom (Frankfurt, Germany)', extra:5},
    de2:{label:'VodaFoam Deutschland (Frankfurt, Germany)', extra:6},
    de3:{label:'O-Zwei Deutschland (Frankfurt, Germany)', extra:7},
    gr:{label:'KozmoteGR (Athens, Greece)', extra:29},
    gr2:{label:'VodaFoam Hellas (Athens, Greece)', extra:30},
    gr3:{label:'NovaNot Hellas (Athens, Greece)', extra:31},
    hu:{label:'Magyer Telekonn (Budapest, Hungary)', extra:16},
    hu2:{label:'VodaFoam Hungary (Budapest, Hungary)', extra:17},
    hu3:{label:'YetiTel Hungary (Budapest, Hungary)', extra:18},
    is:{label:'Siminn+ (Reykjavík, Iceland)', extra:33},
    ie:{label:'Eirlink Communications (Dublin, Ireland)', extra:16},
    ie2:{label:'VodaFoam Éire (Dublin, Ireland)', extra:17},
    ie3:{label:'Thrree Éire (Dublin, Ireland)', extra:18},
    it:{label:'TIMone Italia (Milan, Italy)', extra:16},
    it2:{label:'VodaFoam Italia (Milan, Italy)', extra:17},
    it3:{label:'VentoTre Italia (Milan, Italy)', extra:18},
    xk:{label:'IPKObit (Pristina, Kosovo)', extra:25},
    lv:{label:'TetraNet Latvia (Riga, Latvia)', extra:26},
    li:{label:'LiechtenLink (Vaduz, Liechtenstein)', extra:9},
    lt:{label:'Telija Lietuva (Vilnius, Lithuania)', extra:25},
    lu:{label:'POST+ Lux (Luxembourg City, Luxembourg)', extra:6},
    mt:{label:'GO! Malta+ (Valletta, Malta)', extra:24},
    md:{label:'MoldaTelecom (Chișinău, Moldova)', extra:30},
    mc:{label:'MonaCom (Monaco, Monaco)', extra:11},
    me:{label:'CrnaTelekonn (Podgorica, Montenegro)', extra:23},
    nl:{label:'K.P.Now (Amsterdam, Netherlands)', extra:6},
    nl2:{label:'VodaZiggy Nederland (Amsterdam, Netherlands)', extra:7},
    nl3:{label:'Odid-Oh Nederland (Amsterdam, Netherlands)', extra:8},
    mk:{label:'MaKTel+ (Skopje, North Macedonia)', extra:24},
    no:{label:'TeleNorge+ (Oslo, Norway)', extra:18},
    no2:{label:'TeliaNot Norge (Oslo, Norway)', extra:19},
    no3:{label:'IceE Norge (Oslo, Norway)', extra:20},
    pl:{label:'Orangina Polska (Warsaw, Poland)', extra:14},
    pl2:{label:'Playy Polska (Warsaw, Poland)', extra:15},
    pl3:{label:'T-Mobil-ish Polska (Warsaw, Poland)', extra:16},
    pt:{label:'MEOW Portugal (Lisbon, Portugal)', extra:22},
    pt2:{label:'VodaFoam Portugal (Lisbon, Portugal)', extra:23},
    pt3:{label:'N.O.S.not Portugal (Lisbon, Portugal)', extra:24},
    ro:{label:'DigiWigi (Bucharest, Romania)', extra:22},
    ro2:{label:'Orangina România (Bucharest, Romania)', extra:23},
    ro3:{label:'VodaFoam România (Bucharest, Romania)', extra:24},
    ru:{label:'RosTeleConn (Moscow, Russia)', extra:42},
    sm:{label:'SanMarinoCom (San Marino, San Marino)', extra:15},
    rs:{label:'mtsBit (Belgrade, Serbia)', extra:20},
    sk:{label:'SlovaTel+ (Bratislava, Slovakia)', extra:12},
    sk2:{label:'Orangina Slovensko (Bratislava, Slovakia)', extra:13},
    sk3:{label:'O-Dva Slovensko (Bratislava, Slovakia)', extra:14},
    sk4:{label:'Antika Internet (Bratislava, Slovakia)', extra:226},
    si:{label:'TeleSlovenija+ (Ljubljana, Slovenia)', extra:15},
    es:{label:'MoviStarz (Madrid, Spain)', extra:19},
    es2:{label:'Orangina España (Madrid, Spain)', extra:20},
    es3:{label:'VodaFoam España (Madrid, Spain)', extra:21},
    se:{label:'TeliaNot (Stockholm, Sweden)', extra:17},
    se2:{label:'TeleToo Sverige (Stockholm, Sweden)', extra:18},
    se3:{label:'TeleNorge Sverige (Stockholm, Sweden)', extra:19},
    ch:{label:'SwissConn (Zurich, Switzerland)', extra:8},
    ch2:{label:'SunRised Schweiz (Zurich, Switzerland)', extra:9},
    ch3:{label:'SaltyNet Schweiz (Zurich, Switzerland)', extra:10},
    ua:{label:'KyivStarNet+ (Kyiv, Ukraine)', extra:31},
    gb:{label:'BeeTee Broadband (London, United Kingdom)', extra:11},
    gb2:{label:'VodaFoam UK (London, United Kingdom)', extra:12},
    gb3:{label:'Thrree UK (London, United Kingdom)', extra:13},
    va:{label:'HolySee Broadband (Vatican City, Vatican City)', extra:17},
    // Other regions
    us:{label:'Comcastic Broadband (New York, United States)', extra:82},
    ca:{label:'RogersLand (Toronto, Canada)', extra:88},
    mx:{label:'TelMex+ (Mexico City, Mexico)', extra:95},
    br:{label:'ViVoom Brasil (São Paulo, Brazil)', extra:145},
    ar:{label:'PersonalNet+ (Buenos Aires, Argentina)', extra:155},
    cl:{label:'EntelNot (Santiago, Chile)', extra:160},
    co:{label:'ClaroNot Colombia (Bogotá, Colombia)', extra:130},
    za:{label:'VodaCon SA (Johannesburg, South Africa)', extra:165},
    ng:{label:'MTiN Nigeria (Lagos, Nigeria)', extra:140},
    ke:{label:'SafariConn (Nairobi, Kenya)', extra:155},
    eg:{label:'TelEgypt+ (Cairo, Egypt)', extra:90},
    ma:{label:'MarocTel+ (Casablanca, Morocco)', extra:70},
    tr:{label:'TürkTelekonn (Istanbul, Turkey)', extra:45},
    il:{label:'BeZeqNet (Tel Aviv, Israel)', extra:60},
    ae:{label:'Etisalot (Dubai, UAE)', extra:98},
    sa:{label:'STC+ Arabia (Riyadh, Saudi Arabia)', extra:105},
    qa:{label:'OoreDo+ (Doha, Qatar)', extra:110},
    in:{label:'Jyo Networks (Mumbai, India)', extra:112},
    pk:{label:'PTCLplus (Karachi, Pakistan)', extra:125},
    bd:{label:'GrameenFone+ (Dhaka, Bangladesh)', extra:135},
    cn:{label:'Chyna Telecom (Shanghai, China)', extra:195},
    sg:{label:'SingTell+ (Singapore, Singapore)', extra:172},
    th:{label:'TrueNot Thailand (Bangkok, Thailand)', extra:175},
    vn:{label:'VietTelCo (Ho Chi Minh City, Vietnam)', extra:178},
    ph:{label:'GlobeNot Telecom (Manila, Philippines)', extra:182},
    id:{label:'TelkomSell (Jakarta, Indonesia)', extra:178},
    jp:{label:'SoftBonk Japan (Tokyo, Japan)', extra:188},
    kr:{label:'SKTeleConn (Seoul, South Korea)', extra:183},
    au:{label:'TelStrayta (Sydney, Australia)', extra:212},
    nz:{label:'SparkPlug NZ (Auckland, New Zealand)', extra:220},
    pe:{label:'ClaroNot Peru (Lima, Peru)', extra:150},
    ec:{label:'CNT+ Ecuador (Quito, Ecuador)', extra:145},
    ve:{label:'CANTV+ (Caracas, Venezuela)', extra:150},
    gh:{label:'MTiN Ghana (Accra, Ghana)', extra:150},
    et:{label:'EthioTel+ (Addis Ababa, Ethiopia)', extra:165},
    tz:{label:'VodaCon TZ (Dar es Salaam, Tanzania)', extra:170},
    iq:{label:'ZainNet+ (Baghdad, Iraq)', extra:110},
    ir:{label:'IranCell+ (Tehran, Iran)', extra:115},
    jo:{label:'OrangeJo+ (Amman, Jordan)', extra:100},
    lb:{label:'AlfaNet+ (Beirut, Lebanon)', extra:95},
    lk:{label:'DialogNot (Colombo, Sri Lanka)', extra:130},
    np:{label:'NTC+ Nepal (Kathmandu, Nepal)', extra:140},
    mm:{label:'MPT+ Myanmar (Yangon, Myanmar)', extra:175},
    kh:{label:'SmartAxiCom (Phnom Penh, Cambodia)', extra:178},
    tw:{label:'ChungHwaConn (Taipei, Taiwan)', extra:190},
    hk:{label:'HKTel+ (Hong Kong, Hong Kong)', extra:185},
    mn:{label:'MobiComm MN (Ulaanbaatar, Mongolia)', extra:180},
    kz:{label:'KzCell+ (Almaty, Kazakhstan)', extra:120},
    uz:{label:'BeeLined UZ (Tashkent, Uzbekistan)', extra:125},
    fj:{label:'VodaFiji+ (Suva, Fiji)', extra:230},
    pg:{label:'DigiCel+ PNG (Port Moresby, Papua New Guinea)', extra:225},
  };

// ---------- Weather conditions + which connection types they affect ----------
  const weatherConditions = {
    clear:{label:'Clear Skies', severity:0},
    lightrain:{label:'Light Rain', severity:0.3},
    heavyrain:{label:'Heavy Rain', severity:0.65},
    storm:{label:'Thunderstorm', severity:1.0},
    snow:{label:'Snow', severity:0.5},
    fog:{label:'Dense Fog', severity:0.4},
  };
  const weatherSensitivity = {
    starlink:0.8, starlinkpro:0.8, starlinkmaritime:0.85, starlinkaviation:0.85, starlinkmini:0.8,
    meo:0.7, satellite:0.75, vsat:0.75, directcell:0.6,
    fso:0.9, ptp60g_af:0.85, eband:0.8,
    mmwave:0.6, fiveg_adv:0.4, sixg:0.5,
    wisp10:0.3, wisp20:0.3, wisp45:0.3, wisp60:0.3, wisp100:0.3, wisppro:0.25,
    licensedmw:0.25, ptp24g_af:0.3, ptp5g_af:0.2, ptp11g_af:0.15,
    fixedwireless:0.2, cbrs:0.15, tvws:0.15, mobile5g:0.1, sa5g:0.1,
    lte:0.05, ltea:0.05, ltecat18:0.05, weaksignal:0.15,
  };

// ---------- IP address type (public / CGNAT / dual-stack) per network icon ----------
  const ipTypeByIcon = {
    internet:'ipv4_public', fibre:'dualstack', wifi:'ipv4_public', cable:'ipv4_cgnat',
    satellite:'ipv4_cgnat', tower:'ipv4_public', laser:'ipv4_public', chip:'ipv4_cgnat',
    enterprise:'ipv4_public', switch:'dualstack', submarinecable:'dualstack', rocket:'dualstack',
    mesh:'ipv4_public', latency:'dualstack', bluetooth:'ipv4_public', thunderbolt:'ipv4_public',
    five_g:'dualstack', four_g:'dualstack', three_g:'ipv4_cgnat', two_g:'ipv4_cgnat',
  };

// ---------- Simulated connection-failure presets ----------
  const failurePresets = {
    conn_refused:{code:'ERR_CONN_REFUSED', msg:'Failed to connect to network. Contact your provider for further information.'},
    dns_fail:{code:'ERR_DNS_NXDOMAIN', msg:'Could not resolve the test server address. Check your DNS settings.'},
    timeout:{code:'ERR_CONN_TIMEOUT', msg:'Connection to the test server timed out.'},
    auth_fail:{code:'ERR_AUTH_401', msg:'Authentication failed. Your session with the provider may have expired.'},
    no_signal:{code:'ERR_NO_CARRIER_SIGNAL', msg:'No signal detected from your modem or ONT. Check physical connections.'},
    gateway_unreachable:{code:'ERR_GATEWAY_UNREACHABLE', msg:'Your router or gateway is unreachable. Try restarting it.'},
    server_503:{code:'ERR_SERVER_503', msg:'The test server is temporarily unavailable. Please try again later.'},
    maintenance:{code:'ERR_ISP_MAINTENANCE', msg:'Your provider is performing scheduled maintenance in your area.'},
    rate_limited:{code:'ERR_RATE_LIMIT_429', msg:'Too many test requests. Please wait a moment before retrying.'},
    firewall:{code:'ERR_FIREWALL_BLOCKED', msg:'The connection was blocked by a firewall or security software.'},
    link_down:{code:'ERR_LINK_DOWN', msg:'Network cable or wireless link appears to be down.'},
    suspended:{code:'ERR_ACCOUNT_SUSPENDED', msg:'Your account has been suspended. Contact billing support.'},
    congestion:{code:'ERR_CONGESTION_LOCAL', msg:'Severe network congestion detected in your area.'},
    packet_loss:{code:'ERR_PACKET_LOSS_CRIT', msg:'Critical packet loss prevented a stable connection.'},
    unknown:{code:'ERR_UNKNOWN_0x8007045D', msg:'An unknown error occurred while contacting the server.'},
  };
